#!/bin/sh

mkdir -p "/cw/lvs/NoCsBack/vakken/ac2021/G0B30A/$(whoami)/output_$1" && \
	sed "s/output\//\/cw\/lvs\/NoCsBack\/vakken\/ac2021\/G0B30A\/$(whoami)\/output_$1\//g" "params_$1.par" > params_temp.par && \
	(time sh -c 'mpirun -np 4 ./amrvac -i "params_temp.par" 2> /dev/null') 2> "/cw/lvs/NoCsBack/vakken/ac2021/G0B30A/$(whoami)/output_$1/info.txt" && \
	python3 animate.py "$1"
